# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

    desc "Submit to internal track"
    lane :update_metadata do
        upload_to_play_store(skip_upload_aab: true)
    end

    desc "Submit to internal track"
    lane :internal do
        gradle(task: 'bundle', build_type: 'Release', flags: '--no-daemon')
        upload_to_play_store(track: 'internal')
    end

#     desc "Submit to alpha track"
#     lane :alpha do
#         gradle(task: 'bundle', build_type: 'Release', flags: '--no-daemon')
#         upload_to_play_store(track: 'alpha')
#     end
#
#     desc "Submit to beta track"
#     lane :beta do
#         gradle(task: 'bundle', build_type: 'Release', flags: '--no-daemon')
#         upload_to_play_store(track: 'beta')
#     end

    desc "Submit to production track"
    lane :production do
        gradle(task: 'bundle', build_type: 'Release', flags: '--no-daemon')
        upload_to_play_store
    end

end