# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

    desc "Submit a internal build to Google Play"
    lane :internal do
        gradle(task: 'bundle', build_type: 'Release', flags: '--no-daemon')
        upload_to_play_store(track: 'internal')
    end

#     desc "Submit a alpha build to Google Play"
#     lane :internal do
#         gradle(task: 'bundle', build_type: 'Release', flags: '--no-daemon')
#         upload_to_play_store(track: 'alpha')
#     end
#
#     desc "Submit a beta build to Google Play"
#     lane :internal do
#         gradle(task: 'bundle', build_type: 'Release', flags: '--no-daemon')
#         upload_to_play_store(track: 'beta')
#     end

    desc "Submit a production build to Google Play"
    lane :production do
        gradle(task: 'bundle', build_type: 'Release', flags: '--no-daemon')
        upload_to_play_store
    end

end