name: Fastlane Release

on:
  push:
    branches: [ "release" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
        
    - name: Generate local.properties, google-services.json
      run: |
        echo "$LOCAL_PROPERTIES" > local.properties
        echo "$GOOGLE_SERVICES" > app/google-services.json.b64
        base64 -d -i app/google-services.json.b64 > app/google-services.json
      env:
        LOCAL_PROPERTIES: ${{ secrets.LOCAL_PROPERTIES }}
        GOOGLE_SERVICES: ${{ secrets.GOOGLE_SERVICES }}
        
    - name: Setting env
      run: |
        echo "STORE_PASSWORD=${{ secrets.STORE_PASSWORD }}" >> $GITHUB_ENV
        echo "KEY_ALIAS=${{ secrets.KEY_ALIAS }}" >> $GITHUB_ENV 
        echo "KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}" >> $GITHUB_ENV
        
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6'

    - name: Install Bundle
      run: |
        gem install bundler
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
        
    - name: Generate Credential File for Fastlane
      run: |
        echo "$PLAY_STORE_CREDENTIALS" > play-store-credentials.json.b64
        base64 -d -i play-store-credentials.json.b64 > play-store-credentials.json
      env:
        PLAY_STORE_CREDENTIALS: ${{ secrets.PLAY_STORE_CREDENTIALS }}

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew :app:release
      
    - name: Submit a new Internal Build to Play Store
      run: bundle exec fastlane internal_release
